import 'package:dio/dio.dart' as dio;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:simantap/components/rounded_button.dart';
import 'package:simantap/components/rounded_input_field.dart';
import 'package:simantap/components/rounded_password_field.dart';
import 'package:simantap/models/info_tambahan.dart';
import 'package:simantap/res/constants.dart';
import 'package:simantap/res/theme.dart';
import 'package:simantap/controllers/controllers.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:simantap/utils/random_circle_back.dart';
import 'package:simantap/utils/random_hex_color.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:auto_size_text/auto_size_text.dart';

part 'login/login_screen.dart';
part 'register/register_screen.dart';
part 'home/home_screen.dart';
part 'home/info_tambahan_item.dart';
part 'infotambahandetail/info_tambahan_detail_screen.dart';
part 'infotambahandetail/info_tambahan_detail_item.dart';